version: '3.8'
services:
  dev-database:
    image: 'postgres:15.0'
    container_name: dev-database
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: testdb
    networks:
      - nestjs-networks
  # create another container for "TEST"
  test-database:
    image: 'postgres:15.0'
    container_name: test-database
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: testdb
    networks:
      - nestjs-networks
networks:
  nestjs-networks:
# docker compose up -d
# docker-compose up -d nestjs-api-app_dev-database_1 -d

# docker-compose rm nestjs-api-app_dev-database_1 --stop --force --volumes
